on:
  schedule:
  # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '20 17 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI3ZjMxYjBhOWRiMTA0NmQ5YTk1MzUxZGY4YzRhMGZjZCIsImF1ZCI6Ijc2OTE3Y2NjY2Q0NDQxYzM5NDU3YTA0ZjYwODRmYjJmIiwiZXhwIjoxNjkwNzcxODEwLCJpYXQiOjE2ODI5OTU4MTB9.xZZXBVw457W99vR6CrHwyZt6nBmQgKZe0XMt6vls63C1qaioeqOFT6vDqxRsIx3YJTUl6gOXhWfEb0kTc-SPjg }}
          GP_TOKEN: ${{ secrets.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}}
          PUSH_TYPES: 'pushplus'
          DO_NOT_REWARD: 'false'
          SERVERCHAN_SEND_KEY: ${{ secrets.SERVERCHAN_SEND_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PUSHPLUS_TOKEN: ${{ secrets.cfce0d9ff0de4c0d88fa0fa8192aebae }}
          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_TLS: ${{ secrets.SMTP_TLS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
          SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          CQHTTP_ENDPOINT: ${{ secrets.CQHTTP_ENDPOINT }}
          CQHTTP_USER_ID: ${{ secrets.CQHTTP_USER_ID }}
          CQHTTP_ACCESS_TOKEN: ${{ secrets.CQHTTP_ACCESS_TOKEN }}
